[project]
name = "hypha"
version = "0.0.0"
requires-python = ">=3.13"

[tool.uv.workspace]
members = ["hypha-gui", "hypha-py", "maturin-with-stub"]

[tool.uv.sources]
maturin-with-stub.workspace = true
hypha-py.workspace = true
